os:
  - linux

sudo: false

dist: trusty

addons:
  apt:
    packages:
      - lua5.2

git:
  depth: 4

language: c

install:

script: ./bin/build.sh

deploy:
  - provider: pages # check the site at https://github/teckel12/LuaTelemetry
    github_token: $GITHUB_TOKEN
    skip_cleanup: true

on:
  branch: master
